# Generated by Django 5.0.6 on 2024-07-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyKaro', '0002_alter_catagory_options_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderitem',
        ),
    ]
