# Generated by Django 5.0.6 on 2024-07-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyKaro', '0006_order_total_amount_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
