# Generated by Django 5.0.6 on 2024-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyKaro', '0009_rename_customer_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
