# Generated by Django 5.0.6 on 2024-07-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyKaro', '0011_alter_order_total_price'),
        ('BuyKaro', '0012_alter_order_first_name_alter_order_last_name_and_more'),
    ]

    operations = [
    ]
